# Generated by Django 4.0 on 2021-12-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='이메일 주소')),
                ('username', models.CharField(max_length=30, verbose_name='이름')),
                ('english_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='영문이름')),
                ('birth_day', models.DateField(blank=True, null=True, verbose_name='생년월일')),
                ('resident_registration_number', models.CharField(max_length=7)),
                ('phone', models.CharField(max_length=20, verbose_name='휴대폰 번호')),
                ('home_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='집 주소')),
                ('home_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='집 전화번호')),
                ('company_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='회사 이름')),
                ('company_address', models.CharField(blank=True, max_length=50, null=True, verbose_name='회사 주소')),
                ('company_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='회사 전화번호')),
                ('is_active', models.BooleanField(default=True, verbose_name='계정 활성화 여부')),
                ('is_admin', models.BooleanField(default=False, verbose_name='관리자')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='superuser 권한')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '사용자',
            },
        ),
    ]
